os: linux
dist: bionic
language: shell
git:
  quiet: true
env:
  global:
    - HADOLINT_VERSION=1.19.0
services:
- docker
before_install:
- sudo curl -L https://github.com/hadolint/hadolint/releases/download/v$HADOLINT_VERSION/hadolint-$(uname -s)-$(uname -m) -o /usr/local/bin/hadolint
- sudo chmod 755 /usr/local/bin/hadolint
install:
- docker build
  --no-cache
  --tag aminvakil/sitebroker:${TRAVIS_COMMIT} .
script:
- DOCKERCONTAINER=$(docker run -d aminvakil/sitebroker:${TRAVIS_COMMIT})
- sleep 10
- docker ps -f id=${DOCKERCONTAINER}
- hadolint Dockerfile
- docker stop ${DOCKERCONTAINER} && docker rm -fv ${DOCKERCONTAINER}
after_success:
- docker tag aminvakil/sitebroker:${TRAVIS_COMMIT} quay.io/aminvakil/sitebroker
- docker login quay.io -u="$QUAY_USERNAME" -p="$QUAY_PASSWORD"
- docker push quay.io/aminvakil/sitebroker
